install:
- pip install -U pip
- pip install cookiecutter
- pip --version
- ( cd pydistman && python3 python_pypi_dist_manager.py build_only )
- ( cd pydistman && cat dest/requirements.txt )
- ( cd pydistman && cd dest && pip install -r requirements.txt && pip install
  . )
language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- pypy3
script:
- ( cd pydistman && cd dest && py.test --cov sum_walker --cov-report term-missing tests/ )
